import type React from "react";

const styles: Record<string, React.CSSProperties> = {
  container: {
    textAlign: "center",
    fontFamily: "sans-serif",
    padding: 24,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
  },
  // ── Меню ──
  menuCard: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "16px 20px",
    borderRadius: 14,
    border: "2px solid #e8e8e8",
    background: "#fff",
    cursor: "pointer",
    transition: "border-color 0.2s, box-shadow 0.2s",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
    userSelect: "none",
  },
  menuIcon: {
    fontSize: 36,
    lineHeight: 1,
    flexShrink: 0,
  },
  menuTitle: {
    fontWeight: 700,
    fontSize: 16,
    textAlign: "left" as const,
  },
  menuSub: {
    fontSize: 13,
    color: "#888",
    marginTop: 2,
    textAlign: "left" as const,
  },
  // ── Локальная игра ──
  localPlayerCard: {
    borderRadius: 12,
    padding: "10px 20px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 4,
    minWidth: 110,
    background: "#fafafa",
    transition: "border 0.2s",
    position: "relative" as const,
  },
  turnDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#1677ff",
    position: "absolute" as const,
    bottom: 6,
  },
  nameInput: {
    border: "1px solid #d0d0d0",
    borderRadius: 6,
    padding: "2px 6px",
    fontSize: 13,
    width: 90,
    textAlign: "center" as const,
    outline: "none",
  },
  localStatus: {
    fontSize: 18,
    fontWeight: 700,
    minHeight: 30,
    marginBottom: 14,
  },
  // ── Онлайн-игра ──
  players: {
    display: "flex",
    gap: 32,
    justifyContent: "center",
    alignItems: "stretch",
    marginBottom: 8,
  },
  playerCard: {
    borderRadius: 12,
    padding: "12px 24px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 8,
    minWidth: 140,
    background: "#fafafa",
    transition: "border 0.2s",
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "#f0f0f0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  status: {
    fontSize: 18,
    fontWeight: 600,
    margin: 0,
    minHeight: 28,
  },
  errorBox: {
    background: "#fff2f0",
    border: "1px solid #ffccc7",
    borderRadius: 8,
    padding: "8px 16px",
    color: "#cf1322",
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  closeBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 18,
    color: "#cf1322",
    padding: 0,
  },
};

export default styles;
